Part 1:

In [27]:
#Load the dataset from the CSV file into a Pandas DataFrame.
import pandas as pd
df1 = pd.read_csv("/content/sample_data/california_housing_train.csv")

#Display the first 5 and last 10 rows of the data.
print(df1.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  


In [28]:
print(df1.tail(10))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.

In [29]:
##Get a statistical summary of the dataset to examine the numerical columns.
df1.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [30]:
len(pd.unique(df1["total_bedrooms"]))

1848

In [32]:
new_column = df1["total_bedrooms"]/df1["total_rooms"]
df = df1.copy()
df["total_bedrooms_per_total_rooms"] = new_column
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  \
0      1015.0       472.0         1.4936             66900.0   
1      1129.0       463.0         1.8200             80100.0   
2       333.0       117.0         1.6509             85700.0   
3       515.0       226.0         3.1917             73400.0   
4       624.0       262.0         1.9250             65500.0   

   total_bedrooms_per_total_rooms  
0                        0.228617  
1                        0.248497  
2                        0.241667  
3                   

In [33]:
df["total_bedrooms_per_total_rooms"].mean()

0.21275998821034803

In [34]:
df["total_bedrooms_per_total_rooms"].std()

0.057823008903161756

In [36]:
new_df = df.loc[df["median_income"] > 5]
new_df.describe()

longitude     latitude  housing_median_age   total_rooms  \
count  3752.000000  3752.000000         3752.000000   3752.000000   
mean   -119.604907    35.371279           25.792910   3319.856077   
std       1.997416     1.924250           12.758864   2855.516286   
min    -124.050000    32.570000            1.000000      8.000000   
25%    -121.960000    33.850000           16.000000   1785.000000   
50%    -118.500000    34.190000           25.000000   2579.000000   
75%    -117.950000    37.440000           35.000000   3842.500000   
max    -115.390000    40.940000           52.000000  37937.000000   

       total_bedrooms    population   households  median_income  \
count     3752.000000   3752.000000  3752.000000    3752.000000   
mean       525.973081   1443.458156   502.527985       6.637531   
std        455.779351   1280.078375   422.539744       1.818219   
min          1.000000     11.000000     1.000000       5.001200   
25%        282.750000    769.000000   275.000000       5.418375   
50%        408.000000   1121.000000   395.500000       6.070450   
75%        600.000000   1665.000000   580.000000       7.183250   
max       5471.000000  16122.000000  5189.000000      15.000100   

       median_house_value  total_bedrooms_per_total_rooms  
count         3752.000000                     3752.000000  
mean        329194.360075                        0.160378  
std         111283.812608                        0.026483  
min          47500.000000                        0.100000  
25%         240200.000000                        0.142939  
50%         314000.000000                        0.157607  
75%         420525.000000                        0.173091  
max         500001.000000                        0.459091

In [37]:
new_df2 = df.loc[(df["total_rooms"] > 10000) & (df["median_house_value"] < 150000)]
print(new_df2)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  media

In [41]:
df.to_csv("new_data.csv")

Part 2:


In [43]:
import numpy as np
ar1 = np.array(range(1,21))
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [45]:
ar1[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [53]:
ar2 = np.random.randint(10, 100, size = [4,5])
print(ar2)

[[56 47 11 79 63]
 [10 58 51 78 81]
 [69 59 96 62 36]
 [52 13 31 68 83]]


In [55]:
print(ar2[[0,1,2],:2])

[[56 47]
 [10 58]
 [69 59]]


In [57]:
ar3 = ar1.reshape(4,5)
print(ar3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [58]:
ar4 = ar3.flatten()
print(ar4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [61]:
ar5 = ar1.reshape(5,4)
new_ar = ar3.dot(ar5)
print(new_ar)

[[ 175  190  205  220]
 [ 400  440  480  520]
 [ 625  690  755  820]
 [ 850  940 1030 1120]]


In [64]:
rand_arr = np.random.randint(0,101, size=50)
print(rand_arr)

[57 90 14 32 43 89 33 69 87 94 27 17 97 21 23 26 60 77 25 33 74 80 91 89
 95 77 16 80 26 93  0  3 59  1 66 32 79 88 51 72 68 43 17 67 54 65 52 16
 23 56]


In [69]:
boolean_index = rand_arr > 50
print(rand_arr[boolean_index])

[57 90 89 69 87 94 97 60 77 74 80 91 89 95 77 80 93 59 66 79 88 51 72 68
 67 54 65 52 56]


In [71]:
print(rand_arr[[1,3,4,6,2]])

[90 32 43 33 14]


In [89]:
#taking new_ar as reference here
print(new_ar)
for i in range(0,4):
  ar = new_ar[:,i]
  print(f"Mean, max and sum for column indexed {i} is {np.mean(ar, axis=0)}, {ar.max()}, {ar.sum()} respectively.")

[[ 175  190  205  220]
 [ 400  440  480  520]
 [ 625  690  755  820]
 [ 850  940 1030 1120]]
Mean, max and sum for column indexed 0 is 512.5, 850, 2050 respectively.
Mean, max and sum for column indexed 1 is 565.0, 940, 2260 respectively.
Mean, max and sum for column indexed 2 is 617.5, 1030, 2470 respectively.
Mean, max and sum for column indexed 3 is 670.0, 1120, 2680 respectively.


In [95]:
#My code
# mask = new_ar[:,:] > np.mean(new_ar[:,i])
# print(mask)
# print(new_ar[mask])
#giving a wrong boolean value for 3rd row, 1st column

[[False False False False]
 [False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 690  755  820  850  940 1030 1120]


In [96]:
# Chatgpt
# Compute the mean of each column
column_means = np.mean(new_ar, axis=0)

# Apply the mask: each element should be greater than its respective column mean
mask = new_ar > column_means

# Print the mask
print(mask)

# Print the elements where the mask is True
print(new_ar[mask])


[[False False False False]
 [False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 625  690  755  820  850  940 1030 1120]


Part 3:


In [112]:
fibbo_start = [0,1]
loop_continues = True
i = 0
while loop_continues:
  new_num = fibbo_start[i] + fibbo_start[i+1]
  if new_num <100:
    fibbo_start.append(new_num)
    i+=1
  else:
    loop_continues = False


print(fibbo_start)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [114]:
list1 = []
for i in range(1,51):
  list1.append(i)
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [118]:
n=1
while n <= 50 :
  if n % 3 == 0 and n % 5 == 0 :
    print("FizzBuzz")
  elif n % 3 == 0 :
    print("Fizz")
  elif n % 5 == 0 :
    print("Buzz")
  else:
    print(n)
  n+=1

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


In [1]:
def calculate_mean(total_number):
  list = []
  for i in range(1,int(total_number)+1):
    n1 = int(input("Enter a number: "))
    list.append(n1)

  sum1 = sum(list)
  mean = sum1/total_number
  print(f"The mean is {mean}")

calculate_mean(int(input("For how many numbers do you wish to cslculate the mean: ")))

For how many numbers do you wish to cslculate the mean:  2
Enter a number: 2
Enter a number: 8
The mean is 5.0


In [21]:
#list of numbers
list2=[]

# def check_for_zero(n):
#     if n == 0:
#       return
def calculate_median(total_number):
    for i in range(1,int(total_number)+1):
      n1 = int(input("Enter a number: "))
      list2.append(n1)
      list2.sort()

    a = len(list2)
    if a == 0:
      print("You can't get a median for zero numbersssss")
      return
    elif a % 2 == 0 :
      median = (list2[int(a/2)] +list2[int(a/2) - 1])/2
      print(median)
    else:
      median = list2[int((a+1)/2) - 1]
      print(median)
    print(list2)


calculate_median(int(input("For how many numbers do you want to calculate the median: ")))

For how many numbers do you want to calculate the median: 0
You can't get a median for zero numbersssss
